// Utility file for defining enabled filters for different chart types
// This provides a centralized way to manage which filters are available for each chart type

import { ChartFilterState } from "@/components/dashboards/ChartsFilterSidebar";

// Type for enabled filters
export type EnabledFilters = Array<keyof ChartFilterState>;

// Common filter sets that can be reused across multiple charts
export const COMMON_FILTER_SETS = {
  // Basic filters - common across most charts
  BASIC: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "officer",
  ] as EnabledFilters,

  // Geographic filters - for spatial analysis
  GEOGRAPHIC: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "position",
    "officer",
  ] as EnabledFilters,

  // Severity analysis filters
  SEVERITY: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "province",
    "city",
    "accidentType",
    "officer",
  ] as EnabledFilters,

  // Comprehensive filters - all available filters
  ALL: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,
};

// Specific filter sets for different chart types
export const CHART_SPECIFIC_FILTERS = {
  // Spatial Light Analytics - Based on spatialLightAnalytics API
  SPATIAL_LIGHT_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus", // Key filter for light analytics
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Collision Analytics - Based on collisionAnalytics API
  COLLISION_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "equipmentDamages",
    "vehicleColor",
    "vehicleSystem",
    "vehiclePlaqueType",
    "vehicleSystemType",
    "vehicleFaultStatus",
    "vehicleInsuranceCo",
    "vehiclePlaqueUsage",
    "vehicleBodyInsuranceCo",
    "vehicleMotionDirection",
    "vehicleMaxDamageSections",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
    "driverTotalReason",
    "passengerSex",
    "passengerInjuryType",
    "passengerFaultStatus",
    "passengerTotalReason",
    "pedestrianSex",
    "pedestrianInjuryType",
    "pedestrianFaultStatus",
    "pedestrianTotalReason",
  ] as EnabledFilters,

  // Road Defects Analytics
  ROAD_DEFECTS_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "equipmentDamages",
    "vehicleColor",
    "vehicleSystem",
    "vehiclePlaqueType",
    "vehicleSystemType",
    "vehicleFaultStatus",
    "vehicleInsuranceCo",
    "vehiclePlaqueUsage",
    "vehicleBodyInsuranceCo",
    "vehicleMotionDirection",
    "vehicleMaxDamageSections",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
    "driverTotalReason",
    "officer",
  ] as EnabledFilters,

  // Human Reason Analytics
  HUMAN_REASON_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "accidentType",
    "humanReasons", // Key filter for human reasons
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
    "lightStatus",
    "airStatuses",
    "officer",
  ] as EnabledFilters,

  // Vehicle Reason Analytics - Based on vehicleReasonAnalytics API
  VEHICLE_REASON_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadSurfaceConditions",
    "humanReasons",
    "roadDefects",
    "vehicleSystem", // Key filter for vehicle reasons
    "driverSex",
    "driverLicenceType",
  ] as EnabledFilters,

  // Area Usage Analytics
  AREA_USAGE_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "areaUsages", // Key filter for area usage
    "accidentType",
    "collisionType",
    "lightStatus",
    "roadSituation",
    "officer",
  ] as EnabledFilters,

  // Accident Severity Analytics - Now includes all available filters
  ACCIDENT_SEVERITY_ANALYTICS: [
    // Core Accident Details
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCount",
    "deadCountMin",
    "deadCountMax",
    "injuredCount",
    "injuredCountMin",
    "injuredCountMax",
    "hasWitness",
    "newsNumber",
    "officer",
    "completionDateFrom",
    "completionDateTo",

    // Location & Context
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",

    // Environmental & Reason-based
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "equipmentDamages",
    "roadSurfaceConditions",

    // Attachments
    "attachmentName",
    "attachmentType",

    // Vehicle DTOs Filters
    "vehicleColor",
    "vehicleSystem",
    "vehiclePlaqueType",
    "vehicleSystemType",
    "vehicleFaultStatus",
    "vehicleInsuranceCo",
    "vehicleInsuranceNo",
    "vehiclePlaqueUsage",
    "vehiclePrintNumber",
    "vehiclePlaqueSerialElement",
    "vehicleInsuranceDateFrom",
    "vehicleInsuranceDateTo",
    "vehicleBodyInsuranceCo",
    "vehicleBodyInsuranceNo",
    "vehicleMotionDirection",
    "vehicleBodyInsuranceDateFrom",
    "vehicleBodyInsuranceDateTo",
    "vehicleMaxDamageSections",
    "vehicleDamageSectionOther",
    "vehicleInsuranceWarrantyLimit",
    "vehicleInsuranceWarrantyLimitMin",
    "vehicleInsuranceWarrantyLimitMax",

    // Driver in Vehicle DTOs Filters
    "driverSex",
    "driverFirstName",
    "driverLastName",
    "driverNationalCode",
    "driverLicenceNumber",
    "driverLicenceType",
    "driverInjuryType",
    "driverTotalReason",

    // Passenger in Vehicle DTOs Filters
    "passengerSex",
    "passengerFirstName",
    "passengerLastName",
    "passengerNationalCode",
    "passengerInjuryType",
    "passengerFaultStatus",
    "passengerTotalReason",

    // Pedestrian DTOs Filters
    "pedestrianSex",
    "pedestrianFirstName",
    "pedestrianLastName",
    "pedestrianNationalCode",
    "pedestrianInjuryType",
    "pedestrianFaultStatus",
    "pedestrianTotalReason",
  ] as EnabledFilters,

  // Monthly/Holiday Analytics - Based on monthlyHolidayAnalytics API
  MONTHLY_HOLIDAY_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "equipmentDamages",
    "vehicleColor",
    "vehicleSystem",
    "vehiclePlaqueType",
    "vehicleSystemType",
    "vehicleFaultStatus",
    "vehicleInsuranceCo",
    "vehiclePlaqueUsage",
    "vehicleBodyInsuranceCo",
    "vehicleMotionDirection",
    "vehicleMaxDamageSections",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
    "driverTotalReason",
  ] as EnabledFilters,

  // Hourly/Day of Week Analytics - Based on hourlyDayOfWeekAnalytics API
  HOURLY_DAY_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "equipmentDamages",
    "vehicleColor",
    "vehicleSystem",
    "vehiclePlaqueType",
    "vehicleSystemType",
    "vehicleFaultStatus",
    "vehicleInsuranceCo",
    "vehiclePlaqueUsage",
    "vehicleBodyInsuranceCo",
    "vehicleMotionDirection",
    "vehicleMaxDamageSections",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
    "driverTotalReason",
  ] as EnabledFilters,

  // Company Performance Analytics
  COMPANY_PERFORMANCE_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "vehicleReasons",
    "vehicleSystem",
    "vehicleFaultStatus", // Key filters for vehicle/company analysis
    "collisionType",
    "roadSituation",
    "officer",
  ] as EnabledFilters,

  // Total Reason Analytics - Based on totalReasonAnalytics API
  TOTAL_REASON_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadSurfaceConditions",
    "humanReasons",
    "roadDefects", // Key filters for comprehensive reason analysis
    "vehicleSystem",
    "driverSex",
    "driverLicenceType",
  ] as EnabledFilters,

  // Spatial Collision Analytics - Based on spatialCollisionAnalytics API
  SPATIAL_COLLISION_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType", // Key filter for collision analytics
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Hotspots Analytics - Using comprehensive filters for geographic analysis
  HOTSPOTS_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone", // Key filters for geographic hotspot analysis
    "accidentType",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "limit",
    "skip",
  ] as EnabledFilters,

  // Regional Analytics
  REGIONAL_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone", // Key filters for regional comparison
    "accidentType",
    "collisionType",
    "areaUsages",
    "officer",
  ] as EnabledFilters,

  // Safety Index Analytics - Based on spatialSafetyIndexAnalytics API
  SAFETY_INDEX_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax", // Key filters for safety assessment
    "officer",
    "province",
    "city",
    "cityZone",
    "accidentType",
    "position",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "vehicleSystem",
    "driverSex",
  ] as EnabledFilters,

  // Temporal Count Analytics - Based on temporalCountAnalytics API
  TEMPORAL_COUNT_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "accidentType",
    "collisionType",
    "lightStatus",
    "areaUsages",
    "officer",
  ] as EnabledFilters,

  // Temporal Severity Analytics - Based on temporalSeverityAnalytics API
  TEMPORAL_SEVERITY_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "province",
    "city",
    "road",
    "accidentType",
    "collisionType",
    "officer",
  ] as EnabledFilters,

  // Temporal Night Analytics - Based on temporalNightAnalytics API
  TEMPORAL_NIGHT_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Temporal Collision Analytics - Based on temporalCollisionAnalytics API
  TEMPORAL_COLLISION_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Temporal Damage Analytics - Based on temporalDamageAnalytics API
  TEMPORAL_DAMAGE_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "areaUsages",
    "maxDamageSections",
  ] as EnabledFilters,

  // Temporal Total Reason Analytics - Based on temporalTotalReasonAnalytics API
  TEMPORAL_TOTAL_REASON_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadSurfaceConditions",
    "humanReasons",
    "roadDefects",
    "vehicleSystem",
    "driverSex",
    "driverLicenceType",
    "officer",
  ] as EnabledFilters,

  // Temporal Unlicensed Drivers Analytics - Based on temporalUnlicensedDriversAnalytics API
  TEMPORAL_UNLICENSED_DRIVERS_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Spatial Severity Analytics - Based on spatialSeverityAnalytics API
  SPATIAL_SEVERITY_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Spatial Single Vehicle Analytics - Based on spatialSingleVehicleAnalytics API
  SPATIAL_SINGLE_VEHICLE_ANALYTICS: [
    "seri",
    "serial",
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "officer",
    "province",
    "city",
    "road",
    "trafficZone",
    "cityZone",
    "accidentType",
    "position",
    "rulingType",
    "lightStatus",
    "collisionType",
    "roadSituation",
    "roadRepairType",
    "shoulderStatus",
    "areaUsages",
    "airStatuses",
    "roadDefects",
    "humanReasons",
    "vehicleReasons",
    "roadSurfaceConditions",
    "vehicleSystem",
    "vehicleFaultStatus",
    "driverSex",
    "driverLicenceType",
    "driverInjuryType",
  ] as EnabledFilters,

  // Trend Collision Analytics - For trend analysis of collision types
  TREND_COLLISION_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "collisionType",
    "lightStatus",
    "areaUsages",
    "roadSituation",
    "officer",
  ] as EnabledFilters,

  // Trend Severity Analytics - For trend analysis of accident severity
  TREND_SEVERITY_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "deadCountMin",
    "deadCountMax",
    "injuredCountMin",
    "injuredCountMax",
    "province",
    "city",
    "road",
    "accidentType",
    "collisionType",
    "officer",
  ] as EnabledFilters,

  // Monthly Trend Analytics - For monthly trend analysis
  MONTHLY_TREND_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "accidentType",
    "collisionType",
    "lightStatus",
    "areaUsages",
    "officer",
  ] as EnabledFilters,

  // Yearly Trend Analytics - For yearly trend analysis
  YEARLY_TREND_ANALYTICS: [
    "dateOfAccidentFrom",
    "dateOfAccidentTo",
    "province",
    "city",
    "road",
    "accidentType",
    "collisionType",
    "lightStatus",
    "areaUsages",
    "officer",
  ] as EnabledFilters,
};

// Helper function to get enabled filters for a specific chart type
export const getEnabledFiltersForChart = (
  chartType: keyof typeof CHART_SPECIFIC_FILTERS,
): EnabledFilters => {
  return CHART_SPECIFIC_FILTERS[chartType];
};

// Helper function to combine multiple filter sets
export const combineFilterSets = (
  ...filterSets: EnabledFilters[]
): EnabledFilters => {
  const combined = new Set<keyof ChartFilterState>();
  filterSets.forEach((set) => {
    set.forEach((filter) => combined.add(filter));
  });
  return Array.from(combined);
};

// Helper function to create custom filter set
export const createCustomFilterSet = (
  baseSet: EnabledFilters,
  additions: EnabledFilters = [],
  removals: EnabledFilters = [],
): EnabledFilters => {
  const filterSet = new Set(baseSet);

  // Add additional filters
  additions.forEach((filter) => filterSet.add(filter));

  // Remove specified filters
  removals.forEach((filter) => filterSet.delete(filter));

  return Array.from(filterSet);
};
