import { Feather, Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import type { ComponentProps } from 'react';

export type IonName = ComponentProps<typeof Ionicons>['name'];
export type MdName = ComponentProps<typeof MaterialCommunityIcons>['name'];
export type FeName = ComponentProps<typeof Feather>['name'];
export type IconFamily = 'ion' | 'md' | 'feather';
export type IconName = IonName | MdName | FeName;
export type IconSpec = { family: IconFamily; name: IconName };

const ion = (name: IonName): IconSpec => ({ family: 'ion', name });
const md = (name: MdName): IconSpec => ({ family: 'md', name });

export const AppIcons = {
  nav: {
    back: ion('arrow-forward'),
    chevronLeft: ion('chevron-back'),
    close: ion('close'),
    logout: ion('log-out'),
    refresh: ion('refresh'),
    settings: ion('settings'),
    help: ion('help-circle-outline'),
    support: ion('headset-outline'),
    check: ion('checkmark'),
  },
  status: {
    online: ion('wifi'),
    offline: ion('cloud-offline'),
    gpsOk: ion('location'),
    gpsWeak: ion('location-outline'),
    gpsOff: md('map-marker-off'),
    draft: ion('create-outline'),
    queued: ion('time-outline'),
    syncing: ion('sync'),
    synced: ion('checkmark-circle'),
    rejected: ion('close-circle'),
    failed: ion('alert-circle'),
    warning: ion('warning-outline'),
    error: ion('alert-circle'),
    info: ion('information-circle-outline'),
  },
  home: {
    registerIncident: ion('add-circle'),
    emergency: md('alarm-light'),
    shift: md('clock-time-four-outline'),
    unit: ion('shield-checkmark-outline'),
    vehicle: md('car-side'),
    drafts: ion('folder-open'),
    myReports: ion('documents'),
    announcements: ion('megaphone-outline'),
    mapShortcut: ion('navigate-outline'),
    profile: ion('person-circle'),
    lastSync: ion('cloud-done'),
    offlinePack: ion('cloud-download'),
  },
  map: {
    pinIncident: ion('location'),
    pinOfficer: ion('person-circle'),
    zoomIn: ion('add'),
    zoomOut: ion('remove'),
    locateMe: ion('locate'),
    layers: ion('layers'),
    route: md('directions-fork'),
    direction: md('sign-direction'),
    kilometer: md('highway'),
    distance: ion('swap-horizontal'),
    accuracy: ion('pulse'),
    confirmLocation: ion('checkmark'),
    editLocation: ion('location-outline'),
  },
  phases: {
    basicInfo: ion('clipboard-outline'),
    classification: md('tag'),
    police: md('police-badge-outline'),
    vehicles: ion('car-outline'),
    people: ion('people-outline'),
    environment: md('road-variant'),
    facilityDamage: md('hammer-wrench'),
    readOnly: ion('lock-closed-outline'),
  },
  severity: {
    propertyDamage: md('car-wrench'),
    injury: ion('medkit'),
    fatal: md('coffin'),
  },
  collision: {
    vehicleVehicle: md('car-multiple'),
    vehicleMotorcycle: md('motorbike'),
    vehiclePedestrian: md('walk'),
    vehicleBicycle: md('bike'),
    vehicleFixedObject: md('traffic-cone'),
    rollover: md('rotate-left'),
    runOffRoad: md('arrow-decision-outline'),
    fallFromBridge: md('arrow-collapse-down'),
    multiCollision: md('car-multiple'),
    animal: md('paw'),
    unknown: ion('help-circle-outline'),
  },
  police: {
    present: md('police-badge'),
    station: md('office-building-outline'),
    croquisAmicable: md('handshake-outline'),
    croquisNonAmicable: md('gavel'),
  },
  vehicleType: {
    car: md('car-side'),
    pickup: md('car-pickup'),
    truck: md('truck'),
    trailer: md('truck-trailer'),
    bus: md('bus'),
    minibus: md('bus-school'),
    motorcycle: md('motorbike'),
    roadMachinery: md('excavator'),
    emergencyVehicle: md('car-emergency'),
    other: ion('ellipsis-horizontal'),
  },
  personRole: {
    driver: md('steering'),
    passenger: md('account'),
    pedestrian: md('walk'),
    motorcyclist: md('motorbike'),
    cyclist: md('bike'),
    worker: md('account-hard-hat'),
    other: ion('ellipsis-horizontal'),
  },
  injuryStatus: {
    uninjured: ion('checkmark-circle'),
    minor: md('bandage'),
    serious: md('heart-pulse'),
    critical: md('alert-octagon'),
    deadAtScene: md('coffin'),
    deadAfterTransfer: md('coffin'),
    unknown: ion('help-circle-outline'),
  },
  environment: {
    weather: {
      clear: md('weather-sunny'),
      cloudy: md('weather-cloudy'),
      rainy: md('weather-rainy'),
      foggy: md('weather-fog'),
      dusty: md('weather-hazy'),
      strongWind: md('weather-windy'),
      other: ion('ellipsis-horizontal'),
    },
    lighting: {
      day: md('white-balance-sunny'),
      sunrise: md('weather-sunset-up'),
      sunset: md('weather-sunset-down'),
      nightLit: md('weather-night'),
      nightDark: md('lightbulb-off'),
    },
    surface: {
      dry: md('water-off'),
      moist: md('water-percent'),
      wet: md('water'),
      flooded: md('waves'),
      slippery: md('snowflake-melt'),
      oily: md('oil'),
      debris: md('shovel'),
      unknown: ion('help-circle-outline'),
    },
    geometry: {
      straight: ion('arrow-forward'),
      curve: md('angle-obtuse'),
      uphill: md('slope-uphill'),
      downhill: md('slope-downhill'),
      bridge: md('bridge'),
      tunnel: md('tunnel'),
      ramp: md('stairs-down'),
      tollArea: md('boom-gate'),
      roadwork: md('excavator'),
      intersection: md('call-split'),
      shoulder: md('road-variant'),
    },
    defect: {
      pavement: md('road-variant'),
      markings: md('ruler'),
      signs: md('sign-text'),
      lighting: md('lightbulb-off'),
      guardrail: md('fence'),
      missingBarrier: md('border-none'),
      obstruction: md('block-helper'),
      flooding: md('waves'),
      visibility: ion('eye-off'),
      noneObserved: ion('checkmark-circle'),
      other: ion('ellipsis-horizontal'),
    },
  },
  facility: {
    guardrail: md('fence'),
    jersey: md('wall'),
    sign: md('sign-text'),
    signPost: md('sign-direction'),
    lightPole: md('outdoor-lamp'),
    lightLamp: md('lightbulb-on'),
    fence: md('fence'),
    camera: md('cctv'),
    tollEquipment: md('boom-gate'),
    pavement: md('road-variant'),
    bridge: md('bridge'),
    other: ion('ellipsis-horizontal'),
    immediateHazard: md('flash-alert'),
    needsRepair: md('hammer-wrench'),
    temporaryAction: md('tools'),
  },
  media: {
    plate: md('card-account-details-outline'),
    insurance: md('shield-check-outline'),
    croquis: md('pencil-ruler'),
    damage: md('car-brake-alert'),
    incident: ion('image-outline'),
    camera: ion('camera'),
    gallery: ion('images'),
    preview: ion('eye-outline'),
    replace: ion('sync'),
    delete: ion('trash'),
  },
  announcement: {
    urgent: md('alert-decagram'),
    important: ion('flag'),
    normal: ion('information-circle-outline'),
  },
} as const;
