import { eventSetup } from "./event/mod.ts";
import { fileSetup } from "./file/mod.ts";
import { userSetup } from "./user/mod.ts";
import { organizationSetup } from "./organization/mod.ts";
import { unitSetup } from "./unit/mod.ts";
import { wareSetup } from "./ware/mod.ts";
import { inventorySetup } from "./inventory/mod.ts";
import { consumptionSetup } from "./consumption/mod.ts";
import { goodsReceiptSetup } from "./goods_receipt/mod.ts";
import { goodsRequestSetup } from "./goods_request/mod.ts";
import { stockMovementSetup } from "./stock_movement/mod.ts";
import { citySetup } from "./city/mod.ts";
import { townshipSetup } from "./township/mod.ts";
import { provinceSetup } from "./province/mod.ts";
import { roadSetup } from "./road/mod.ts";
import { colorSetup } from "./color/mod.ts";
import { airStatusSetup } from "./air_status/mod.ts";
import { areaUsageSetup } from "./area_usage/mod.ts";
import { airPollutionZoneSetup } from "./air_pollution_zone/mod.ts";
import { bodyInsuranceCoSetup } from "./body_insurance_co/mod.ts";
import { cityZoneSetup } from "./city_zone/mod.ts";
import { collisionTypeSetup } from "./collision_type/mod.ts";
import { equipmentDamageSetup } from "./equipment_damage/mod.ts";
import { faultStatusSetup } from "./fault_status/mod.ts";
import { humanReasonSetup } from "./human_reason/mod.ts";
import { insuranceCoSetup } from "./insurance_co/mod.ts";
import { licenceTypeSetup } from "./licence_type/mod.ts";
import { lightStatusSetup } from "./light_status/mod.ts";
import { maxDamageSectionSetup } from "./max_damage_section/mod.ts";
import { motionDirectionSetup } from "./motion_direction/mod.ts";
import { plaqueTypeSetup } from "./plaque_type/mod.ts";
import { plaqueUsageSetup } from "./plaque_usage/mod.ts";
import { positionSetup } from "./position/mod.ts";
import { roadRepairTypeSetup } from "./road_repair_type/mod.ts";
import { roadDefectSetup } from "./road_defect/mod.ts";
import { roadSituationSetup } from "./road_situation/mod.ts";
import { roadSurfaceConditionSetup } from "./road_surface_condition/mod.ts";
import { rulingTypeSetup } from "./ruling_type/mod.ts";
import { shoulderStatusSetup } from "./shoulder_status/mod.ts";
import { systemSetup } from "./system/mod.ts";
import { systemTypeSetup } from "./system_type/mod.ts";
import { trafficZoneSetup } from "./traffic_zone/mod.ts";
import { typeSetup } from "./type/mod.ts";
import { vehicleReasonSetup } from "./vehicle_reason/mod.ts";
import { accidentSetup } from "./accident/mod.ts";
import { accidentProcessSetup } from "./accident_process/mod.ts";
import { appModulesSetup } from "./app_modules/mod.ts";
import { sharedSetup } from "./shared/mod.ts";
import { patrolUnitSetup } from "./patrol_unit/mod.ts";
import { shiftSetup } from "./shift/mod.ts";
import { vehicleSetup } from "./vehicle/mod.ts";
import { patrolOperationsSetup } from "./patrol_operations/mod.ts";
import { announcementSetup } from "./announcement/mod.ts";
import { policeStationSetup } from "./police_station/mod.ts";
import { emergencySetup } from "./emergency/mod.ts";

export const functionsSetup = () => {
	sharedSetup();
	appModulesSetup();
	organizationSetup();
	unitSetup();
	wareSetup();
	inventorySetup();
	consumptionSetup();
	goodsReceiptSetup();
	goodsRequestSetup();
	stockMovementSetup();
	patrolUnitSetup();
	shiftSetup();
	vehicleSetup();
	patrolOperationsSetup();
	policeStationSetup();
	emergencySetup();
	airPollutionZoneSetup();
	airStatusSetup();
	areaUsageSetup();
	bodyInsuranceCoSetup();
	citySetup();
	townshipSetup();
	cityZoneSetup();
	collisionTypeSetup();
	colorSetup();
	equipmentDamageSetup();
	eventSetup();
	faultStatusSetup();
	fileSetup();
	humanReasonSetup();
	insuranceCoSetup();
	licenceTypeSetup();
	lightStatusSetup();
	maxDamageSectionSetup();
	motionDirectionSetup();
	plaqueTypeSetup();
	plaqueUsageSetup();
	positionSetup();
	provinceSetup();
	roadSetup();
	roadDefectSetup();
	roadRepairTypeSetup();
	roadSituationSetup();
	roadSurfaceConditionSetup();
	rulingTypeSetup();
	shoulderStatusSetup();
	systemSetup();
	systemTypeSetup();
	trafficZoneSetup();
	typeSetup();
	userSetup();
	vehicleReasonSetup();
	accidentSetup();
	accidentProcessSetup();
	announcementSetup();
};
