import { accidentSeverityAnalyticsSetup } from "./accidentSeverityAnalytics/mod.ts";
import { areaUsageAnalyticsSetup } from "./areaUsageAnalytics/mod.ts";
import { collisionAnalyticsSetup } from "./collisionAnalytics/mod.ts";
import { companyPerformanceAnalyticsSetup } from "./companyPerformanceAnalytics/mod.ts";
import { eventCollisionAnalyticsSetup } from "./eventCollisionAnalytics/mod.ts";
import { eventSeverityAnalyticsSetup } from "./eventSeverityAnalytics/mod.ts";
import { hourlyDayOfWeekAnalyticsSetup } from "./hourlyDayOfWeekAnalytics/mod.ts";
import { humanReasonAnalyticsSetup } from "./humanReasonAnalytics/mod.ts";
import { monthlyHolidayAnalyticsSetup } from "./monthlyHolidayAnalytics/mod.ts";
import { roadDefectsAnalyticsSetup } from "./roadDefectsAnalytics/mod.ts";
import { roadDefectsAnalyticsWithCountSetup } from "./roadDefectsAnalyticsFnWithCount/mod.ts";
import { spatialCollisionAnalyticsSetup } from "./spatialCollisionAnalytics/mod.ts";
import { spatialLightAnalyticsSetup } from "./spatialLightAnalytics/mod.ts";
import { spatialSeverityAnalyticsSetup } from "./spatialSeverityAnalytics/mod.ts";
import { spatialSingleVehicleAnalyticsSetup } from "./spatialSingleVehicleAnalytics/mod.ts";
import { temporalCollisionAnalyticsSetup } from "./temporalCollisionAnalytics/mod.ts";
import { temporalCountAnalyticsSetup } from "./temporalCountAnalytics/mod.ts";
import { temporalDamageAnalyticsSetup } from "./temporalDamageAnalytics/mod.ts";
import { temporalNightAnalyticsSetup } from "./temporalNightAnalytics/mod.ts";
import { temporalSeverityAnalyticsSetup } from "./temporalSeverityAnalytics/mod.ts";
import { temporalTotalReasonAnalyticsSetup } from "./temporalTotalReasonAnalytics/mod.ts";
import { temporalUnlicensedDriversAnalyticsSetup } from "./temporalUnlicensedDriversAnalytics/mod.ts";
import { totalReasonAnalyticsSetup } from "./totalReasonAnalytics/mod.ts";
import { vehicleReasonAnalyticsSetup } from "./vehicleReasonAnalytics/mod.ts";

export const chartSetup = () => {
	roadDefectsAnalyticsSetup();
	roadDefectsAnalyticsWithCountSetup();
	monthlyHolidayAnalyticsSetup();
	hourlyDayOfWeekAnalyticsSetup();
	collisionAnalyticsSetup();
	accidentSeverityAnalyticsSetup();
	totalReasonAnalyticsSetup();
	humanReasonAnalyticsSetup();
	vehicleReasonAnalyticsSetup();
	areaUsageAnalyticsSetup();
	companyPerformanceAnalyticsSetup();
	temporalCountAnalyticsSetup();
	temporalSeverityAnalyticsSetup();
	temporalNightAnalyticsSetup();
	temporalCollisionAnalyticsSetup();
	temporalDamageAnalyticsSetup();
	temporalTotalReasonAnalyticsSetup();
	temporalUnlicensedDriversAnalyticsSetup();
	spatialSeverityAnalyticsSetup();
	spatialLightAnalyticsSetup();
	spatialCollisionAnalyticsSetup();
	spatialSingleVehicleAnalyticsSetup();
	eventSeverityAnalyticsSetup();
	eventCollisionAnalyticsSetup();
};
