/**
 * The icon set this builder can draw, imported one at a time.
 *
 * Explicit imports rather than a namespace import: the package ships several
 * thousand glyphs, and a wildcard would pull the lot into the bundle.
 *
 * The keys are exactly `FORM_ICON_NAMES` from `@forms` — the shared vocabulary the
 * backend validates a definition against and the patrol app renders. A key the
 * package does not ship renders as a blank box on a device, so the map is checked
 * against the registry rather than trusted.
 */

import {
	CarIcon,
	TruckIcon,
	MotorcycleIcon,
	BicycleIcon,
	BusIcon,
	AmbulanceIcon,
	TrafficSignalIcon,
	WarningIcon,
	WarningOctagonIcon,
	FireIcon,
	BombIcon,
	FirstAidIcon,
	DropIcon,
	SunIcon,
	MoonIcon,
	SunHorizonIcon,
	MoonStarsIcon,
	CloudIcon,
	CloudRainIcon,
	CloudSnowIcon,
	CloudFogIcon,
	CloudLightningIcon,
	WindIcon,
	ThermometerIcon,
	DropHalfIcon,
	SnowflakeIcon,
	GaugeIcon,
	EyeIcon,
	RoadHorizonIcon,
	PathIcon,
	SignpostIcon,
	TrafficSignIcon,
	BarricadeIcon,
	BridgeIcon,
	MountainsIcon,
	TrafficConeIcon,
	LadderIcon,
	WallIcon,
	NavigationArrowIcon,
	MapPinIcon,
	WrenchIcon,
	HammerIcon,
	GearIcon,
	EngineIcon,
	BatteryChargingIcon,
	GasPumpIcon,
	AnchorIcon,
	PlugIcon,
	HardHatIcon,
	ShovelIcon,
	PaintBrushIcon,
	PersonIcon,
	UsersIcon,
	UserFocusIcon,
	SkullIcon,
	SyringeIcon,
	BabyIcon,
	WheelchairIcon,
	PawPrintIcon,
	StethoscopeIcon,
	HeartIcon,
	HeartbeatIcon,
	ClipboardTextIcon,
	NotePencilIcon,
	CalendarBlankIcon,
	ClockIcon,
	PhoneIcon,
	TagIcon,
	PackageIcon,
	CameraIcon,
	ImageIcon,
	VideoCameraIcon,
	PaperPlaneTiltIcon,
	BugIcon,
	LightbulbIcon,
	FileTextIcon,
	CheckCircleIcon,
	XCircleIcon,
	InfoIcon,
	QuestionIcon,
} from "@phosphor-icons/react";

import { FORM_ICON_NAMES, type FormIconName } from "@forms";

export const FORM_ICON_MAP: Record<FormIconName, unknown> = {
	car: CarIcon,
	truck: TruckIcon,
	motorcycle: MotorcycleIcon,
	bicycle: BicycleIcon,
	bus: BusIcon,
	ambulance: AmbulanceIcon,
	trafficSignal: TrafficSignalIcon,
	warning: WarningIcon,
	warningOctagon: WarningOctagonIcon,
	fire: FireIcon,
	bomb: BombIcon,
	firstAid: FirstAidIcon,
	drop: DropIcon,
	sun: SunIcon,
	moon: MoonIcon,
	sunHorizon: SunHorizonIcon,
	moonStars: MoonStarsIcon,
	cloud: CloudIcon,
	cloudRain: CloudRainIcon,
	cloudSnow: CloudSnowIcon,
	cloudFog: CloudFogIcon,
	cloudLightning: CloudLightningIcon,
	wind: WindIcon,
	thermometer: ThermometerIcon,
	dropHalf: DropHalfIcon,
	snowflake: SnowflakeIcon,
	gauge: GaugeIcon,
	eye: EyeIcon,
	roadHorizon: RoadHorizonIcon,
	path: PathIcon,
	signpost: SignpostIcon,
	trafficSign: TrafficSignIcon,
	barricade: BarricadeIcon,
	bridge: BridgeIcon,
	mountains: MountainsIcon,
	trafficCone: TrafficConeIcon,
	ladder: LadderIcon,
	wall: WallIcon,
	navigationArrow: NavigationArrowIcon,
	mapPin: MapPinIcon,
	wrench: WrenchIcon,
	hammer: HammerIcon,
	gear: GearIcon,
	engine: EngineIcon,
	batteryCharging: BatteryChargingIcon,
	gasPump: GasPumpIcon,
	anchor: AnchorIcon,
	plug: PlugIcon,
	hardHat: HardHatIcon,
	shovel: ShovelIcon,
	paintBrush: PaintBrushIcon,
	person: PersonIcon,
	users: UsersIcon,
	userFocus: UserFocusIcon,
	skull: SkullIcon,
	syringe: SyringeIcon,
	baby: BabyIcon,
	wheelchair: WheelchairIcon,
	pawPrint: PawPrintIcon,
	stethoscope: StethoscopeIcon,
	heart: HeartIcon,
	heartbeat: HeartbeatIcon,
	clipboardText: ClipboardTextIcon,
	notePencil: NotePencilIcon,
	calendarBlank: CalendarBlankIcon,
	clock: ClockIcon,
	phone: PhoneIcon,
	tag: TagIcon,
	package: PackageIcon,
	camera: CameraIcon,
	image: ImageIcon,
	videoCamera: VideoCameraIcon,
	paperPlaneTilt: PaperPlaneTiltIcon,
	bug: BugIcon,
	lightbulb: LightbulbIcon,
	fileText: FileTextIcon,
	checkCircle: CheckCircleIcon,
	xCircle: XCircleIcon,
	info: InfoIcon,
	question: QuestionIcon,
};

/** Every shared name resolves to a real component, and nothing extra is exported. */
export const formIconMapIsComplete = (): boolean => {
	const keys = Object.keys(FORM_ICON_MAP).sort();
	const expected = [...FORM_ICON_NAMES].sort();
	return keys.length === expected.length &&
		keys.every((key, index) => key === expected[index]);
};
