/**
 * -----------------------------------------------------------------------------
 * FILE: hourlyDayOfWeekAnalytics.fn.ts (Aggregation Version)
 * -----------------------------------------------------------------------------
 * DESCRIPTION:
 * This function uses a single, efficient MongoDB Aggregation Pipeline to
 * calculate the number of accidents for each hour of each day of the week.
 *
 * It works by:
 * 1.  Setting a default time range to the last full year if none is provided.
 * 2.  Filtering documents based on comprehensive user criteria.
 * 3.  Grouping the documents by a composite key of { dayOfWeek, hour }.
 * 4.  Formatting the results into a series array suitable for an ApexCharts heatmap.
 */
import type { ActFn, Document } from "@deps";
import { accident } from "../../../../mod.ts";
import moment from "npm:jalali-moment";

export const hourlyDayOfWeekAnalyticsFn: ActFn = async (body) => {
	const { set: filters } = body.details;

	// --- 1. Set Default Date Range ---
	let startDate, endDate;
	if (!filters.dateOfAccidentFrom && !filters.dateOfAccidentTo) {
		const now = moment();
		const lastYear = now.jYear() - 1;
		startDate = moment(`${lastYear}/01/01`, "jYYYY/jMM/jDD").startOf("day")
			.toDate();
		endDate = moment(`${lastYear}/12/01`, "jYYYY/jMM/jDD").endOf("jMonth")
			.endOf("day").toDate();
	} else {
		startDate = moment(filters.dateOfAccidentFrom).startOf("day").toDate();
		endDate = moment(filters.dateOfAccidentTo).endOf("day").toDate();
	}

	// --- 2. Build Comprehensive Filter ---
	const matchFilter: Document = {
		date_of_accident: { $gte: startDate, $lte: endDate },
	};
	// Add other filters from the validator...
	if (filters.province && filters.province.length > 0) {
		matchFilter["province.name"] = { $in: filters.province };
	}
	// ... complete with all other filters from your countFn ...

	// --- 3. Define and Execute the Aggregation Pipeline ---
	const pipeline: Document[] = [
		// Stage 1: Filter documents based on user criteria.
		{ $match: matchFilter },

		// Stage 2: Group by a composite key of day of week and hour of day.
		{
			$group: {
				_id: {
					// Note: MongoDB's $dayOfWeek returns Sunday=1, Saturday=7
					// Note: MongoDB's $hour returns 0-23
					dayOfWeek: {
						$dayOfWeek: {
							date: "$date_of_accident",
							timezone: "Asia/Tehran",
						},
					},
					hour: {
						$hour: {
							date: "$date_of_accident",
							timezone: "Asia/Tehran",
						},
					},
				},
				count: { $sum: 1 },
			},
		},
		// Stage 3: Project to a more convenient format.
		{
			$project: {
				_id: 0,
				day: "$_id.dayOfWeek",
				hour: "$_id.hour",
				count: "$count",
			},
		},
	];

	const dbResults = await accident.aggregation({ pipeline }).toArray();

	// --- 4. Format Data for ApexCharts Heatmap ---
	const daysOfWeek = [
		{ name: "شنبه", dbIndex: 7 },
		{ name: "جمعه", dbIndex: 6 },
		{ name: "پنج شنبه", dbIndex: 5 },
		{ name: "چهار شنبه", dbIndex: 4 },
		{ name: "سه شنبه", dbIndex: 3 },
		{ name: "دوشنبه", dbIndex: 2 },
		{ name: "یکشنبه", dbIndex: 1 },
	];

	// Initialize the series structure with all zeros
	const series = daysOfWeek.map((day) => ({
		name: day.name,
		data: Array(24).fill(0),
	}));

	// Populate the series with the results from the database
	for (const result of dbResults) {
		const dayIndex = daysOfWeek.findIndex((d) => d.dbIndex === result.day);
		const hour = result.hour;

		if (dayIndex !== -1 && hour >= 0 && hour < 24) {
			series[dayIndex].data[hour] = result.count;
		}
	}

	return {
		series: series.reverse(), // Reverse to have Sunday at the top and Saturday at the bottom
		// X-axis labels (hours) will be generated by the frontend from 0 to 23.
	};
};
