import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { MapComparisonProvider } from "@/context/MapComparisonContext";
import { BasemapProvider } from "@/context/BasemapContext";
import { Toaster } from "react-hot-toast";
import { Navbar } from "@/components/organisms/Navbar";
import { Footer } from "@/components/organisms/NewFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <BasemapProvider>
          <MapComparisonProvider>
            <AuthProvider>
              <div className="min-h-screen flex flex-col bg-slate-950">
                <Navbar />
                <div className="flex-1 mt-16">{children}</div>
                <Footer />
              </div>
              <Toaster position="top-center" reverseOrder={false} />
            </AuthProvider>
          </MapComparisonProvider>
        </BasemapProvider>
      </body>
    </html>
  );
}
