import { addUserSetup } from "./addUser/mod.ts";
import { changeUserPasswordSetup } from "./changeUserPassword/mod.ts";
import { getMeSetup } from "./getMe/mod.ts";
import { getUserSetup } from "./getUser/mod.ts";
import { loginUserSetup } from "./login/mod.ts";
import { registerUserSetup } from "./register/mod.ts";
import { tempUserSetup } from "./tempUser/mod.ts";
import { setGhostPasswordSetup } from "./setGhostPassword/mod.ts";
import { updateUserSetup } from "./updateUser/mod.ts";
import { getUsersSetup } from "./getUsers/mod.ts";
import { removeUserSetup } from "./removeUser/mod.ts";
import { countUsersSetup } from "./countUsers/mod.ts";
import { updateUserRelationsSetup } from "./updateUserRelations/mod.ts";
import { dashboardStatisticSetup } from "./dashboardStatistic/mod.ts";
import { seedSetup } from "./seed/mod.ts";

export const userSetup = () => {
	addUserSetup();
	getMeSetup();
	getUserSetup();
	loginUserSetup();
	tempUserSetup();
	setGhostPasswordSetup();
	updateUserSetup();
	registerUserSetup();
	changeUserPasswordSetup();
	getUsersSetup();
	removeUserSetup();
	countUsersSetup();
	updateUserRelationsSetup();
	dashboardStatisticSetup();
	seedSetup();
};
