import { coreApp } from "../mod.ts";
import {
	boolean,
	date,
	defaulted,
	optional,
	type RelationDataType,
	type RelationSortOrderType,
	string,
} from "@deps";
import { createUpdateAt } from "../utils/createUpdateAt.ts";
import { user_excludes } from "@model";

export const device_pure = {
	device_id: string(), // unique device identifier generated by the app
	fingerprint: string(), // device fingerprint / secure device token
	platform: string(), // ios | android
	app_version: string(), // e.g. "1.0.0"
	model: string(), // device model name (e.g. iPhone 14)
	is_active: defaulted(boolean(), true),
	last_seen_at: defaulted(date(), () => new Date()),
	registered_at: defaulted(date(), () => new Date()),
	revoked_at: optional(date()), // set when the session is remotely revoked
	// FCM/APNs push token for announcement & sync-result notifications.
	// Refreshed on every device-scoped login.
	push_token: optional(string()),

	...createUpdateAt,
};

export const device_relations = {
	owner: {
		schemaName: "user",
		type: "single" as RelationDataType,
		optional: false,
		excludes: user_excludes,
		relatedRelations: {
			devices: {
				type: "multiple" as RelationDataType,
				limit: 50,
				sort: {
					field: "_id",
					order: "desc" as RelationSortOrderType,
				},
			},
		},
	},
};

export const devices = () =>
	coreApp.odm.newModel("device", device_pure, device_relations, {
		createIndex: {
			indexSpec: { device_id: 1 },
			options: { unique: true, sparse: true },
		},
	});
